#!/usr/bin/env node

import { componentize } from '@bytecodealliance/componentize-js';
import { readFile, writeFile } from 'node:fs/promises';
const jsSource = await readFile('extension.js', 'utf8');
const { component } = await componentize(jsSource, {
  witPath: "./wit",
  worldName: "extension"
});
await writeFile('extension.wasm', component);
